#!/usr/bin/env python3
# Project: Hierarchical Reasoning Model for Puzzle Solving
# Authors: Kyrylo Kozlovskyi (G00425385), Fionn McCarthy (G00414386)
# Supervisor: Dr. John Healy
# Institution: Atlantic Technological University
# Duration: 2025/2026

"""
Maze Visualizer
Visualizes maze datasets generated by maze_generator.py

Usage:
    python maze_visualizer.py maze_dataset.npz
    python maze_visualizer.py maze_dataset.npz --num 5
    python maze_visualizer.py maze_dataset.npz --index 3 5 7
    python maze_visualizer.py maze_dataset.npz --no-color --show-matrices
"""

import argparse
import numpy as np
import sys


class MazeVisualizer:
    """Visualizer for maze datasets."""

    def __init__(self, use_color=True):
        self.use_color = use_color
        self._setup_symbols()

    def _setup_symbols(self):
        """Set up display symbols based on color preference."""
        if self.use_color:
            self.WALL = "\033[90m██\033[0m"  # Dark gray
            self.PATH = "\033[37m· \033[0m"  # Light gray
            self.START = "\033[92mS \033[0m"  # Green
            self.EXIT = "\033[91mE \033[0m"  # Red
            self.SOLUTION = "\033[93m* \033[0m"  # Yellow
            self.EMPTY = "\033[90m· \033[0m"  # Dark gray
        else:
            self.WALL = "██"
            self.PATH = "· "
            self.START = "S "
            self.EXIT = "E "
            self.SOLUTION = "* "
            self.EMPTY = "· "

    def print_maze(self, maze, solution=None):
        """Print maze with optional solution overlay."""
        for y, row in enumerate(maze):
            for x, cell in enumerate(row):
                if cell == -1:
                    print(self.WALL, end="")
                elif cell == -2:
                    print(self.START, end="")
                elif cell == 0:
                    print(self.EXIT, end="")
                elif solution is not None and solution[y, x] == 1:
                    print(self.SOLUTION, end="")
                else:
                    print(self.PATH, end="")
            print()

    def print_solution(self, maze, solution):
        """Print solution overlaid on maze structure."""
        for y, row in enumerate(solution):
            for x, cell in enumerate(row):
                maze_cell = maze[y, x]
                if maze_cell == -1:
                    print(self.WALL, end="")
                elif maze_cell == -2:
                    print(self.START, end="")
                elif maze_cell == 0:
                    print(self.EXIT, end="")
                elif cell == 1:
                    print(self.SOLUTION, end="")
                else:
                    print(self.EMPTY, end="")
            print()

    def print_legend(self):
        """Print the symbol legend."""
        if self.use_color:
            print(
                f"Legend: \033[90m██\033[0m=wall  \033[92mS\033[0m=start  \033[91mE\033[0m=exit  \033[93m*\033[0m=solution  \033[37m·\033[0m=open"
            )
        else:
            print("Legend: ██=wall  S=start  E=exit  *=solution  ·=open")

    def visualize_maze(self, maze, solution, index=0, show_matrices=False):
        """Visualize a single maze with its solution."""
        height, width = maze.shape

        # Find start and exit positions
        start_pos = tuple(np.argwhere(maze == -2)[0])
        exit_pos = tuple(np.argwhere(maze == 0)[0])
        path_length = int(np.sum(solution == 1))

        print(f"\n{'='*60}")
        print(f"MAZE #{index}")
        print(f"{'='*60}")
        print(
            f"Size: {width}x{height} | Start: {start_pos} | Exit: {exit_pos} | Path length: {path_length}"
        )
        self.print_legend()

        print(f"\n--- Problem (with solution overlay) ---")
        self.print_maze(maze, solution)

        print(f"\n--- Solution only ---")
        self.print_solution(maze, solution)

        if show_matrices:
            print(f"\n--- Problem matrix ---")
            print(maze)
            print(f"\n--- Solution matrix ---")
            print(solution)

    def visualize_dataset(self, problems, solutions, indices=None, show_matrices=False):
        """Visualize multiple mazes from arrays."""
        num_mazes = len(problems)

        if indices is None:
            indices = range(num_mazes)

        print(f"\nVisualizing {len(indices)} of {num_mazes} mazes...")

        for i in indices:
            if i < 0 or i >= num_mazes:
                print(f"Warning: Index {i} out of range (0-{num_mazes-1}), skipping...")
                continue
            self.visualize_maze(problems[i], solutions[i], index=i, show_matrices=show_matrices)


def load_dataset(filepath):
    """Load a maze dataset from file."""
    if filepath.endswith(".npz"):
        data = np.load(filepath)
        return data["problems"], data["solutions"]
    elif filepath.endswith(".npy"):
        # Assume it's the problems file, look for solutions
        if "_problems" in filepath:
            solutions_path = filepath.replace("_problems", "_solutions")
        else:
            solutions_path = filepath.replace(".npy", "_solutions.npy")
            filepath = filepath.replace(".npy", "_problems.npy")

        problems = np.load(filepath)
        solutions = np.load(solutions_path)
        return problems, solutions
    else:
        raise ValueError(f"Unsupported file format: {filepath}")


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Visualize maze datasets in the terminal",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Visualize first 3 mazes from a dataset
  python maze_visualizer.py maze_dataset.npz

  # Visualize first 10 mazes
  python maze_visualizer.py maze_dataset.npz --num 10

  # Visualize specific mazes by index
  python maze_visualizer.py maze_dataset.npz --index 0 5 10 15

  # Visualize without colors (for non-ANSI terminals)
  python maze_visualizer.py maze_dataset.npz --no-color

  # Show raw matrices alongside visualization
  python maze_visualizer.py maze_dataset.npz --show-matrices

  # Combine options
  python maze_visualizer.py maze_dataset.npz --num 5 --no-color --show-matrices
        """,
    )

    parser.add_argument("dataset", type=str, help="Path to maze dataset file (.npz or .npy)")

    parser.add_argument(
        "-n",
        "--num",
        type=int,
        default=3,
        help="Number of mazes to visualize from start (default: 3)",
    )

    parser.add_argument(
        "-i",
        "--index",
        type=int,
        nargs="+",
        default=None,
        help="Specific maze indices to visualize (overrides --num)",
    )

    parser.add_argument("--no-color", action="store_true", help="Disable colored output")

    parser.add_argument("--show-matrices", action="store_true", help="Show raw numpy matrices")

    parser.add_argument(
        "--info", action="store_true", help="Show dataset info only, no visualization"
    )

    return parser.parse_args()


def main():
    args = parse_args()

    # Load dataset
    try:
        problems, solutions = load_dataset(args.dataset)
    except FileNotFoundError:
        print(f"Error: File not found: {args.dataset}")
        sys.exit(1)
    except Exception as e:
        print(f"Error loading dataset: {e}")
        sys.exit(1)

    num_mazes = len(problems)
    height, width = problems[0].shape

    # Show dataset info
    print("=" * 60)
    print("MAZE DATASET INFO")
    print("=" * 60)
    print(f"File: {args.dataset}")
    print(f"Number of mazes: {num_mazes}")
    print(f"Maze dimensions: {width}x{height}")
    print(f"Problems shape: {problems.shape}")
    print(f"Solutions shape: {solutions.shape}")

    if args.info:
        # Just show info, don't visualize
        return

    # Create visualizer
    visualizer = MazeVisualizer(use_color=not args.no_color)

    # Determine which mazes to show
    if args.index is not None:
        indices = args.index
    else:
        indices = list(range(min(args.num, num_mazes)))

    # Visualize
    visualizer.visualize_dataset(
        problems, solutions, indices=indices, show_matrices=args.show_matrices
    )

    print(f"\n{'='*60}")
    print(f"Showed {len(indices)} of {num_mazes} mazes")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
